apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  selector:
    app: mqtt-broker
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 30083
  - name: websocket
    port: 8181
    targetPort: 8181
    nodePort: 30008
  type: NodePort
