apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
spec:
  selector:
    matchLabels:
      app: mqtt-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1    # Add this line
            preference:  # Add this line
              matchExpressions:
              - key: name
                operator: In
                values:
                - group6pi


      containers:
      - name: mqtt-broker
        image: websocket-hivemq:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 1883
        - containerPort: 8181
